spring:
  application:
    name: concert
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/concert_db
    username: root
    password: concert2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: never
queue:
  processing:
    capacity: 30
    rate:
      minutes: 1
token:
  processing:
    valid:
      minutes: 5
  expire:
    rate:
      minutes: 1
concert:
  schedules:
    read:
      limit: 10
  seats:
    read:
      limit: 20
