global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: mysqld-exporter
    scrape_interval: 3s
    static_configs:
      - targets:
          - 172.10.0.5:9104
  - job_name: redis-exporter
    static_configs:
      - targets:
        - 172.10.0.8:9121
  - job_name: kafka
    static_configs:
      - targets:
        - 172.10.0.14:9308
  - job_name: otel_collector
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - collector:8889
